POST http://localhost:8000/api/otpverify
Content-Type: application/json

{
  "id": -49,
  "otp": "826044",
  "phone": "08123456789"
}

###
POST http://localhost:8000/api/otp
Content-Type: application/json

{
  "id": -49,
  "phone": "08123456789"
}

###
