POST http://localhost:8000/api/otpverify
Content-Type: application/json

{
  "id": -2,
  "otp": "5917"
}

###
POST http://localhost:8000/api/otp
Content-Type: application/json

{
  "id": -2,
  "phone": "1234567890"
}

###
