POST http://localhost:8001/api/otpverify
Content-Type: application/json

{
  "id": 3,
  "otp": "9948"
}

###
POST http://localhost:8001/api/otp
Content-Type: application/json

{
  "id": 3,
  "phone": "628123456789"
}

###
